version: '3'
services:
  db1:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=pvDung
      - POSTGRES_DB=BTTH
  webth:
    build: ./Client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/usr/src/BTTH/Client
    links: 
      - webapith
  webapith:
    build: ./serverapi
    ports:
      - "8080:8080"
    volumes:
      - ./serverapi:/usr/src/BTTH/serverapi
    links:
      - db1
    depends_on:
      - "db1"
    command: ["./wait-for-it.sh", "db:5432", "--", "node server.js"]