version: '3'
services:
  db1:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=pvDung
      - POSTGRES_DB=BTTH
  mgdb:
    image: mongo
    ports: 
      - "27017:27017"
  webth:
    build: ./Client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/usr/src/BTTH/Client
    links: 
      - webapith
  webapith:
    build: ./serverapi
    ports:
      - "8080:8080"
    volumes:
      - ./serverapi:/usr/src/BTTH/serverapi
    links:
      - db1
    depends_on:
      - "db1"
      - "mgdb"
    command: ["./wait-for-it.sh", "db1:5432","--", "node server.js"]
  webmgdbth:
    build: ./serverMongoDB
    ports:
      - "8081:8081"
    volumes:
      - ./serverMongoDB:/usr/src/BTTH/serverMongoDB
    links:
      - mgdb
    depends_on:
      - "mgdb"
    command: ["./wait-for-it.sh", "mgdb:27017","--", "node server.js"]